export const TEAM = {
  ana:      { name: 'Ana Bastos',   initials: 'AB', color: '#E8472A' },
  joao:     { name: 'João',         initials: 'JO', color: '#185FA5' },
  pedro:    { name: 'Pedro Nasser', initials: 'PN', color: '#533AB7' },
  jonathan: { name: 'Jonathan',     initials: 'JN', color: '#854F0B' },
  lucas:    { name: 'Lucas',        initials: 'LC', color: '#3B6D11' },
  carol:    { name: 'Carol',        initials: 'CA', color: '#993556' },
  daniel:   { name: 'Daniel',       initials: 'DT', color: '#0F6E56' },
  barbara:  { name: 'Bárbara',      initials: 'BA', color: '#993556' },
  bassani:  { name: 'Bassani',      initials: 'BS', color: '#0F6E56' },
  andre:    { name: 'André',        initials: 'AN', color: '#185FA5' },
  filipe:   { name: 'Filipe',       initials: 'FI', color: '#533AB7' },
  tolentino:{ name: 'Tolentino',    initials: 'TO', color: '#854F0B' },
  vitor:    { name: 'Vitor',        initials: 'VI', color: '#3B6D11' },
  arthur:   { name: 'Arthur',       initials: 'AR', color: '#854F0B' },
  eduardo:  { name: 'Eduardo',      initials: 'ED', color: '#185FA5' },
}

const T = TEAM

export const CAMPAIGNS = [
  {
    id: 'c1',
    name: 'Alfaiataria — de volta aos estoques',
    fase: 'Produção',
    lancamento: '2026-07-06',
    encerramento: '2026-07-07',
    progress: 60,
    risco: 'OK',
    alertCount: 0,
    meta: 30000,
    fases: [
      { name: 'Estratégia',     status: 'done' },
      { name: 'Kickoff',        status: 'done' },
      { name: 'Produção',       status: 'active' },
      { name: 'Pré-lançamento', status: 'pending' },
      { name: 'Live',           status: 'pending' },
      { name: 'Retrospectiva',  status: 'pending' },
    ],
  },
  {
    id: 'c2',
    name: 'Camiseta 2.0 — relançamento',
    fase: 'Produção',
    lancamento: '2026-07-10',
    encerramento: '2026-07-12',
    progress: 35,
    risco: 'OK',
    alertCount: 0,
    meta: 100000,
    fases: [
      { name: 'Estratégia',     status: 'done' },
      { name: 'Kickoff',        status: 'done' },
      { name: 'Produção',       status: 'active' },
      { name: 'Pré-lançamento', status: 'pending' },
      { name: 'Live',           status: 'pending' },
      { name: 'Retrospectiva',  status: 'pending' },
    ],
  },
  {
    id: 'c2b',
    name: 'Comfort — de volta aos estoques',
    fase: 'Produção',
    lancamento: '2026-07-10',
    encerramento: '2026-07-11',
    progress: 45,
    risco: 'OK',
    alertCount: 0,
    meta: 80000,
    fases: [
      { name: 'Estratégia',     status: 'done' },
      { name: 'Kickoff',        status: 'done' },
      { name: 'Produção',       status: 'active' },
      { name: 'Pré-lançamento', status: 'pending' },
      { name: 'Live',           status: 'pending' },
      { name: 'Retrospectiva',  status: 'pending' },
    ],
  },
  {
    id: 'c3',
    name: 'Aumento de preços',
    fase: 'Produção',
    lancamento: '2026-07-13',
    encerramento: '2026-07-31',
    progress: 28,
    risco: 'HIGH',
    alertCount: 4,
    meta: 5940500,
    metaMidia: 761234,
    fases: [
      { name: 'Estratégia',     status: 'done' },
      { name: 'Kickoff',        status: 'done' },
      { name: 'Produção',       status: 'active' },
      { name: 'Pré-lançamento', status: 'pending' },
      { name: 'Live',           status: 'pending' },
      { name: 'Retrospectiva',  status: 'pending' },
    ],
  },
  {
    id: 'c4',
    name: 'Polo — de volta aos estoques',
    fase: 'Produção',
    lancamento: '2026-07-17',
    encerramento: '2026-07-19',
    progress: 40,
    risco: 'MEDIUM',
    alertCount: 1,
    meta: 40000,
    fases: [
      { name: 'Estratégia',     status: 'done' },
      { name: 'Kickoff',        status: 'done' },
      { name: 'Produção',       status: 'active' },
      { name: 'Pré-lançamento', status: 'pending' },
      { name: 'Live',           status: 'pending' },
      { name: 'Retrospectiva',  status: 'pending' },
    ],
  },
  {
    id: 'c5',
    name: 'Urgência — Último dia',
    fase: 'Kickoff',
    lancamento: '2026-07-26',
    encerramento: '2026-07-31',
    progress: 15,
    risco: 'MEDIUM',
    alertCount: 1,
    meta: null,
    fases: [
      { name: 'Estratégia',     status: 'done' },
      { name: 'Kickoff',        status: 'active' },
      { name: 'Produção',       status: 'pending' },
      { name: 'Pré-lançamento', status: 'pending' },
      { name: 'Live',           status: 'pending' },
      { name: 'Retrospectiva',  status: 'pending' },
    ],
  },
]

export const ALERTS = [
  {
    id: 'a1',
    campanhaId: 'c3',
    campanha: 'Aumento de preços',
    severidade: 'HIGH',
    tipo: 'ATRASADA',
    tarefa: 'Criativos Camiseta — 20 vídeos + 10 estáticos',
    responsavel: T.jonathan,
    diasAtraso: 3,
    cascata: [
      { name: 'Criativos Camiseta', status: 'ATRASADA' },
      { name: 'Meta Ads ABO Camiseta', status: 'BLOQUEADA' },
      { name: 'Ativação 13/07', status: 'EM_RISCO' },
    ],
  },
  {
    id: 'a2',
    campanhaId: 'c3',
    campanha: 'Aumento de preços',
    severidade: 'HIGH',
    tipo: 'BLOQUEADA',
    tarefa: 'Landing Pages — Camiseta, Polo, Pijama, Comfort',
    responsavel: T.tolentino,
    diasAtraso: 0,
    cascata: [
      { name: 'LPs bloqueadas — aguardando ID Visual', status: 'BLOQUEADA' },
      { name: 'Meta Ads ABO — destino sem página', status: 'EM_RISCO' },
    ],
  },
  {
    id: 'a3',
    campanhaId: 'c3',
    campanha: 'Aumento de preços',
    severidade: 'MEDIUM',
    tipo: 'EM_RISCO',
    tarefa: 'Pop Up A/B — urgência aumento de preços',
    responsavel: T.tolentino,
    diasAtraso: 0,
    cascata: [
      { name: 'Pop Up A/B', status: 'EM_RISCO' },
      { name: 'ID Visual ainda não entregue', status: 'BLOQUEADA' },
    ],
  },
  {
    id: 'a4',
    campanhaId: 'c3',
    campanha: 'Aumento de preços',
    severidade: 'MEDIUM',
    tipo: 'ATRASADA',
    tarefa: 'Validar disparos com IA até 13/07 — WhatsApp',
    responsavel: T.daniel,
    diasAtraso: 1,
    cascata: [
      { name: 'Validação disparo IA', status: 'ATRASADA' },
      { name: 'Cronograma CRM última semana', status: 'EM_RISCO' },
    ],
  },
  {
    id: 'a5',
    campanhaId: 'c4',
    campanha: 'Polo — de volta aos estoques',
    severidade: 'MEDIUM',
    tipo: 'EM_RISCO',
    tarefa: 'Criativos Polo — aprovação anúncios antigos',
    responsavel: T.andre,
    diasAtraso: 0,
    cascata: [
      { name: 'Aprovação criativos Polo', status: 'EM_RISCO' },
    ],
  },
  {
    id: 'a6',
    campanhaId: 'c5',
    campanha: 'Urgência — Último dia',
    severidade: 'MEDIUM',
    tipo: 'EM_RISCO',
    tarefa: 'Brief copy urgência — Pedro Nasser (à definir)',
    responsavel: T.pedro,
    diasAtraso: 0,
    cascata: [
      { name: 'Copy urgência', status: 'EM_RISCO' },
      { name: 'Criativos último dia', status: 'EM_RISCO' },
    ],
  },
]

export const TASKS_C1 = [
  // ESTRATÉGIA
  { id: 'c3t1',  name: 'Brief estratégico — Aumento de preços',               fase: 'Estratégia',     responsavel: T.ana,       status: 'done',       due: '2026-07-01', real: 'CONCLUIDA',  etapaLimitante: true },
  { id: 'c3t2',  name: 'Definição de produtos e argumentação',                 fase: 'Estratégia',     responsavel: T.joao,      status: 'done',       due: '2026-07-02', real: 'CONCLUIDA' },
  { id: 'c3t3',  name: 'Metas e alocação de verba — R$761k mídia',             fase: 'Estratégia',     responsavel: T.bassani,   status: 'done',       due: '2026-07-03', real: 'CONCLUIDA',  etapaLimitante: true },
  { id: 'c3t4',  name: 'Aprovação estratégia — João',                          fase: 'Estratégia',     responsavel: T.joao,      status: 'done',       due: '2026-07-04', real: 'CONCLUIDA',  etapaLimitante: true },
  // KICKOFF
  { id: 'c3t5',  name: 'Briefing copy — Pedro Nasser',                         fase: 'Kickoff',        responsavel: T.pedro,     status: 'done',       due: '2026-07-05', real: 'CONCLUIDA' },
  { id: 'c3t6',  name: 'Briefing ID Visual — Ana Bastos',                      fase: 'Kickoff',        responsavel: T.ana,       status: 'done',       due: '2026-07-05', real: 'CONCLUIDA',  etapaLimitante: true },
  { id: 'c3t7',  name: 'Planejamento canais — Bassani',                        fase: 'Kickoff',        responsavel: T.bassani,   status: 'done',       due: '2026-07-06', real: 'CONCLUIDA' },
  { id: 'c3t8',  name: '✅ HANDOFF Brief → Produção',                          fase: 'Kickoff',        responsavel: T.ana,       status: 'done',       due: '2026-07-07', real: 'CONCLUIDA',  isHandoff: true },
  // PRODUÇÃO — DESIGN
  { id: 'c3t9',  name: 'ID Visual campanha — Ana Bastos',                      fase: 'Produção',       responsavel: T.ana,       status: 'em revisão', due: '2026-07-08', real: 'ATRASADA',  diasRestantes: -1, etapaLimitante: true },
  { id: 'c3t10', name: 'Criativos Camiseta — 20 vídeos + 10 estáticos',        fase: 'Produção',       responsavel: T.jonathan,  status: 'em criação', due: '2026-07-09', real: 'ATRASADA',  diasRestantes: -3, etapaLimitante: true },
  { id: 'c3t11', name: 'UGC Camiseta — 10 hooks (base + aquisição)',            fase: 'Produção',       responsavel: T.vitor,     status: 'em criação', due: '2026-07-10', real: 'EM_RISCO',  diasRestantes: 1 },
  { id: 'c3t12', name: 'Criativos Polo — 10 vídeos + 10 estáticos',            fase: 'Produção',       responsavel: T.lucas,     status: 'em criação', due: '2026-07-10', real: 'OK',        diasRestantes: 1 },
  { id: 'c3t13', name: 'UGC Polo — 5 hooks',                                   fase: 'Produção',       responsavel: T.vitor,     status: 'em criação', due: '2026-07-10', real: 'OK',        diasRestantes: 1 },
  { id: 'c3t14', name: 'Criativos Comfort — 10 vídeos + 10 estáticos',         fase: 'Produção',       responsavel: T.lucas,     status: 'em criação', due: '2026-07-10', real: 'OK',        diasRestantes: 1 },
  { id: 'c3t15', name: 'UGC Comfort — 5 hooks',                                fase: 'Produção',       responsavel: T.vitor,     status: 'em criação', due: '2026-07-10', real: 'OK',        diasRestantes: 1 },
  { id: 'c3t16', name: 'Criativos demais produtos — 2 vídeos + 5 estáticos',   fase: 'Produção',       responsavel: T.lucas,     status: 'em criação', due: '2026-07-11', real: 'OK',        diasRestantes: 2 },
  // PRODUÇÃO — COPY
  { id: 'c3t17', name: 'Copy hero — narrativa aumento de preços',              fase: 'Produção',       responsavel: T.pedro,     status: 'em criação', due: '2026-07-08', real: 'EM_RISCO',  diasRestantes: 1, etapaLimitante: true },
  { id: 'c3t18', name: 'Copy ads — variações aquisição e base',                fase: 'Produção',       responsavel: T.pedro,     status: 'pendente',   due: '2026-07-10', real: 'OK',        diasRestantes: 1 },
  { id: 'c3t19', name: 'Copy e-mail flow completo',                            fase: 'Produção',       responsavel: T.pedro,     status: 'pendente',   due: '2026-07-10', real: 'OK',        diasRestantes: 1 },
  { id: 'c3t20', name: 'Copy WhatsApp — base e leads',                         fase: 'Produção',       responsavel: T.pedro,     status: 'pendente',   due: '2026-07-10', real: 'OK',        diasRestantes: 1 },
  // PRODUÇÃO — SITE
  { id: 'c3t21', name: 'Banner HP — A/B (collections vs camiseta)',            fase: 'Produção',       responsavel: T.tolentino, status: 'pendente',   due: '2026-07-09', real: 'BLOQUEADA', etapaLimitante: true },
  { id: 'c3t22', name: 'Menu — botão pulsante "Aumento de preços"',            fase: 'Produção',       responsavel: T.tolentino, status: 'pendente',   due: '2026-07-09', real: 'BLOQUEADA' },
  { id: 'c3t23', name: 'Seção aumento de preços + mais vendidos reordenados',  fase: 'Produção',       responsavel: T.tolentino, status: 'pendente',   due: '2026-07-09', real: 'BLOQUEADA' },
  { id: 'c3t24', name: 'Tag "Aumento de preços em breve" nos produtos',        fase: 'Produção',       responsavel: T.tolentino, status: 'pendente',   due: '2026-07-10', real: 'OK',        diasRestantes: 1 },
  { id: 'c3t25', name: 'Mini Cart — OB produtos que vão aumentar de preço',    fase: 'Produção',       responsavel: T.tolentino, status: 'pendente',   due: '2026-07-10', real: 'OK',        diasRestantes: 1 },
  { id: 'c3t26', name: 'Pop Up A/B — urgência aumento de preços',              fase: 'Produção',       responsavel: T.tolentino, status: 'pendente',   due: '2026-07-10', real: 'EM_RISCO',  diasRestantes: 1 },
  { id: 'c3t27', name: 'PDPs — caixa vermelha (1ª compra) e preta (recompra)', fase: 'Produção',       responsavel: T.tolentino, status: 'pendente',   due: '2026-07-10', real: 'BLOQUEADA', etapaLimitante: true },
  { id: 'c3t28', name: 'LPs — Camiseta, Polo, Pijama e Comfort',               fase: 'Produção',       responsavel: T.tolentino, status: 'pendente',   due: '2026-07-11', real: 'BLOQUEADA', etapaLimitante: true },
  { id: 'c3t29', name: 'Collections — banner + seção produtos campanha',       fase: 'Produção',       responsavel: T.tolentino, status: 'pendente',   due: '2026-07-11', real: 'OK',        diasRestantes: 2 },
  { id: 'c3t30', name: 'Checkout — OB produtos com aumento',                   fase: 'Produção',       responsavel: T.tolentino, status: 'pendente',   due: '2026-07-11', real: 'OK',        diasRestantes: 2 },
  // PRODUÇÃO — MÍDIA PAGA
  { id: 'c3t31', name: 'Meta Ads — ABO Camiseta (TOF + BOF)',                  fase: 'Produção',       responsavel: T.andre,     status: 'pendente',   due: '2026-07-11', real: 'BLOQUEADA', etapaLimitante: true },
  { id: 'c3t32', name: 'Meta Ads — ABO Polo',                                  fase: 'Produção',       responsavel: T.andre,     status: 'pendente',   due: '2026-07-11', real: 'BLOQUEADA' },
  { id: 'c3t33', name: 'Meta Ads — ABO Comfort',                               fase: 'Produção',       responsavel: T.andre,     status: 'pendente',   due: '2026-07-11', real: 'BLOQUEADA' },
  { id: 'c3t34', name: 'Meta Ads — ABO demais produtos',                       fase: 'Produção',       responsavel: T.andre,     status: 'pendente',   due: '2026-07-11', real: 'BLOQUEADA' },
  { id: 'c3t35', name: 'Meta Ads — campanha base (todos os produtos)',          fase: 'Produção',       responsavel: T.andre,     status: 'pendente',   due: '2026-07-11', real: 'BLOQUEADA' },
  { id: 'c3t36', name: 'Google Ads — PMAX + GR',                               fase: 'Produção',       responsavel: T.filipe,    status: 'pendente',   due: '2026-07-11', real: 'OK',        diasRestantes: 2 },
  { id: 'c3t37', name: 'Google Ads — YouTube TOF + retargeting demais',        fase: 'Produção',       responsavel: T.filipe,    status: 'pendente',   due: '2026-07-11', real: 'OK',        diasRestantes: 2 },
  // PRODUÇÃO — CRM
  { id: 'c3t38', name: 'E-mail flow — todos produtos, escalar os bons',        fase: 'Produção',       responsavel: T.daniel,    status: 'em criação', due: '2026-07-11', real: 'OK',        diasRestantes: 2 },
  { id: 'c3t39', name: 'WhatsApp — supressão reduzida para 14 dias',           fase: 'Produção',       responsavel: T.daniel,    status: 'em criação', due: '2026-07-12', real: 'OK',        diasRestantes: 3 },
  { id: 'c3t40', name: 'Validar disparos com IA até 13/07',                    fase: 'Produção',       responsavel: T.daniel,    status: 'atrasado',   due: '2026-07-10', real: 'ATRASADA',  diasRestantes: -1, etapaLimitante: true },
  { id: 'c3t41', name: 'Fluxos — checkout, welcome, pageview atualizados',     fase: 'Produção',       responsavel: T.barbara,   status: 'pendente',   due: '2026-07-12', real: 'OK',        diasRestantes: 3 },
  // PRODUÇÃO — SOCIAL + INFLUENCIADORES
  { id: 'c3t42', name: 'Social — calendário 100% aumento de preços',           fase: 'Produção',       responsavel: T.carol,     status: 'em criação', due: '2026-07-10', real: 'OK',        diasRestantes: 1 },
  { id: 'c3t43', name: 'Social — bio, manychat, automação seguidores',         fase: 'Produção',       responsavel: T.carol,     status: 'pendente',   due: '2026-07-11', real: 'OK',        diasRestantes: 2 },
  { id: 'c3t44', name: 'Influenciadores — briefing grandes, pequenos, permuta, afiliados', fase: 'Produção', responsavel: T.vitor, status: 'em criação', due: '2026-07-10', real: 'OK', diasRestantes: 1 },
  // PRODUÇÃO — COMERCIAL / B2B
  { id: 'c3t45', name: 'B2B — disparo base + funil (copy aumento)',            fase: 'Produção',       responsavel: T.barbara,   status: 'pendente',   due: '2026-07-12', real: 'OK',        diasRestantes: 3 },
  { id: 'c3t46', name: 'B2B — email 19h dia 13 para corporativos',             fase: 'Produção',       responsavel: T.barbara,   status: 'pendente',   due: '2026-07-13', real: 'OK',        diasRestantes: 4 },
  { id: 'c3t47', name: 'Comercial — recuperar propostas relevantes',           fase: 'Produção',       responsavel: T.barbara,   status: 'pendente',   due: '2026-07-12', real: 'OK',        diasRestantes: 3 },
  // HANDOFF + PRÉ-LANÇAMENTO
  { id: 'c3t48', name: '✅ HANDOFF Design → Canais',                           fase: 'Produção',       responsavel: T.ana,       status: 'pendente',   due: '2026-07-12', real: 'EM_RISCO',  diasRestantes: 3, isHandoff: true, etapaLimitante: true },
  { id: 'c3t49', name: 'Checklist pré-lançamento — 100%',                      fase: 'Pré-lançamento', responsavel: T.ana,       status: 'pendente',   due: '2026-07-12', real: 'OK',        diasRestantes: 3, etapaLimitante: true },
  { id: 'c3t50', name: 'QA Site — tags, banners, pop up, LP',                  fase: 'Pré-lançamento', responsavel: T.tolentino, status: 'pendente',   due: '2026-07-12', real: 'OK',        diasRestantes: 3 },
  { id: 'c3t51', name: 'QA Meta Ads — criativos, segmentação, páginas',        fase: 'Pré-lançamento', responsavel: T.andre,     status: 'pendente',   due: '2026-07-12', real: 'OK',        diasRestantes: 3 },
  { id: 'c3t52', name: 'Aprovação final — João',                               fase: 'Pré-lançamento', responsavel: T.joao,      status: 'pendente',   due: '2026-07-13', real: 'OK',        diasRestantes: 4, etapaLimitante: true },
  // LIVE
  { id: 'c3t53', name: 'Ativação coordenada D0 — 13/07',                       fase: 'Live',           responsavel: T.bassani,   status: 'pendente',   due: '2026-07-13', real: 'OK',        diasRestantes: 4, etapaLimitante: true },
  { id: 'c3t54', name: 'Escala verba Meta Ads — primeiros 3 dias',             fase: 'Live',           responsavel: T.andre,     status: 'pendente',   due: '2026-07-16', real: 'OK',        diasRestantes: 7 },
  { id: 'c3t55', name: 'Monitoramento ROAS diário + receita Shopify vs meta',  fase: 'Live',           responsavel: T.bassani,   status: 'pendente',   due: '2026-07-20', real: 'OK',        diasRestantes: 11 },
  { id: 'c3t56', name: 'Comercial — escala última semana presencial',          fase: 'Live',           responsavel: T.barbara,   status: 'pendente',   due: '2026-07-26', real: 'OK',        diasRestantes: 17 },
  // RETROSPECTIVA
  { id: 'c3t57', name: 'Debriefing — coleta de dados por canal',               fase: 'Retrospectiva',  responsavel: T.ana,       status: 'pendente',   due: '2026-08-03', real: 'OK',        diasRestantes: 25 },
  { id: 'c3t58', name: 'Documentar aprendizados e atualizar Launchpad',        fase: 'Retrospectiva',  responsavel: T.ana,       status: 'pendente',   due: '2026-08-05', real: 'OK',        diasRestantes: 27 },
]

export const METRICS_DASH = {
  campanhasAtivas: 6,
  tasksNoPrazo: 61,
  alertasCriticos: 2,
  handoffsPendentes: 1,
  proximoLancamento: { nome: 'Alfaiataria — de volta aos estoques', dias: 7 },
  totalTasks: 58,
  tasksConcluidas: 8,
  sparkline: [35, 38, 40, 42, 44, 48, 52, 55, 58, 59, 61, 61],
}
